import L from "leaflet";

const createCircularIcon = (imageUrl) =>
  new L.Icon({
    iconUrl: imageUrl,
    iconSize: [30, 30],
    className: "circular-icon",
  });

const otherPoints = [
  {
    position: [47.3885, 8.5771],
    description: "Elefantenhaus",
    type: "animals",
    icon: createCircularIcon(require("./icons/animals-icon.png")),
    distance: "200m",
  },
  {
    position: [47.3865, 8.5732],
    description: "Löwengehege",
    type: "animals",
    icon: createCircularIcon(require("./icons/animals-icon.png")),
    distance: "550m",
  },
  {
    position: [47.3852, 8.5747],
    description: "Pinguinanlage",
    type: "animals",
    icon: createCircularIcon(require("./icons/animals-icon.png")),
    distance: "400m",
  },
  {
    position: [47.3845, 8.5724],
    description: "Känguru",
    type: "animals",
    icon: createCircularIcon(require("./icons/animals-icon.png")),
    distance: "400m",
  },
  {
    position: [47.3846, 8.5787],
    description: "Regenwaldtiere",
    type: "animals",
    icon: createCircularIcon(require("./icons/animals-icon.png")),
    distance: "1.2km",
  },
  {
    position: [47.3845, 8.5739],
    description: "WC Eingang",
    type: "toilet",
    icon: createCircularIcon(require("./icons/toilet-icon.png")),
    distance: "50m",
  },
  {
    position: [47.3845, 8.5719],
    description: "WC Australien",
    type: "toilet",
    icon: createCircularIcon(require("./icons/toilet-icon.png")),
    distance: "200m",
  },
  {
    position: [47.3873, 8.5739],
    description: "WC Ziege",
    type: "toilet",
    icon: createCircularIcon(require("./icons/toilet-icon.png")),
    distance: "600m",
  },
  {
    position: [47.3873, 8.5753],
    description: "WC Kloster",
    type: "toilet",
    icon: createCircularIcon(require("./icons/toilet-icon.png")),
    distance: "600m",
  },
  {
    position: [47.3884, 8.5771],
    description: "WC Elefant",
    type: "toilet",
    icon: createCircularIcon(require("./icons/toilet-icon.png")),
    distance: "1.2km",
  },
  {
    position: [47.3870, 8.5785],
    description: "WC Savanne",
    type: "toilet",
    icon: createCircularIcon(require("./icons/toilet-icon.png")),
    distance: "1.2km",
  },
  {
    position: [47.3850, 8.5790],
    description: "WC Masoala",
    type: "toilet",
    icon: createCircularIcon(require("./icons/toilet-icon.png")),
    distance: "1.2km",
  },
  {
    position: [47.3843, 8.5738],
    description: "Shop",
    type: "shop",
    icon: createCircularIcon(require("./icons/shop-icon.png")),
    distance: "300m",
  },
  {
    position: [47.3843, 8.578],
    description: "Masoala Shop",
    type: "shop",
    icon: createCircularIcon(require("./icons/shop-icon.png")),
    distance: "1.2km",
  },
  {
    position: [47.3842, 8.5767],
    description: "Parking Nord",
    type: "park",
    icon: createCircularIcon(require("./icons/park-icon.png")),
    distance: "200m",
  },
  {
    position: [47.3838, 8.5772],
    description: "Parking Süd",
    type: "park",
    icon: createCircularIcon(require("./icons/park-icon.png")),
    distance: "180m",
  },
  {
    position: [47.3863, 8.5735],
    description: "Picnic Kamel",
    type: "food",
    icon: createCircularIcon(require("./icons/food-icon.png")),
    distance: "400m",
  },
  {
    position: [47.3867, 8.574],
    description: "Picnic Ziege",
    type: "food",
    icon: createCircularIcon(require("./icons/food-icon.png")),
    distance: "600m",
  },
  {
    position: [47.3867, 8.5765],
    description: "Picnic Savanne",
    type: "food",
    icon: createCircularIcon(require("./icons/food-icon.png")),
    distance: "1.5km",
  },
  {
    position: [47.3865, 8.5775],
    description: "Picnic Savanne",
    type: "food",
    icon: createCircularIcon(require("./icons/food-icon.png")),
    distance: "1.5km",
  },
  {
    position: [47.3847, 8.5725],
    description: "Picnic Australien",
    type: "food",
    icon: createCircularIcon(require("./icons/food-icon.png")),
    distance: "200m",
  },
  {
    position: [47.388, 8.5778],
    description: "Picnic Elefant",
    type: "food",
    icon: createCircularIcon(require("./icons/food-icon.png")),
    distance: "2km",
  },
  {
    position: [47.3848, 8.5738],
    description: "Service Point",
    type: "service_point",
    icon: createCircularIcon(require("./icons/servicepoint-icon.png")),
    distance: "180m",
  },
  {
    position: [47.3845, 8.5718],
    description: "Service Point",
    type: "service_point",
    icon: createCircularIcon(require("./icons/servicepoint-icon.png")),
    distance: "250m",
  },
  {
    position: [47.3868, 8.5744],
    description: "Service Point",
    type: "service_point",
    icon: createCircularIcon(require("./icons/servicepoint-icon.png")),
    distance: "360m",
  },
  {
    position: [47.3876, 8.577],
    description: "Service Point",
    type: "service_point",
    icon: createCircularIcon(require("./icons/servicepoint-icon.png")),
    distance: "720m",
  },
  {
    position: [47.3883, 8.575],
    description: "Service Point",
    type: "service_point",
    icon: createCircularIcon(require("./icons/servicepoint-icon.png")),
    distance: "950m",
  },
  {
    position: [47.3871, 8.5788],
    description: "Service Point",
    type: "service_point",
    icon: createCircularIcon(require("./icons/servicepoint-icon.png")),
    distance: "1km",
  },
  {
    position: [47.385, 8.579],
    description: "Service Point",
    type: "service_point",
    icon: createCircularIcon(require("./icons/servicepoint-icon.png")),
    distance: "1.5km",
  },
];

export default otherPoints;
